export const routes = {
  home: "/",
  login: "/dang-nhap",
  register: "/dang-ky",
  forgot: "/quen-mat-khau",
  changePassword: "/doi-mat-khau",
  faq: "/faq",
  size: "/huong-dan-do-ni",
  bst: "/bo-suu-tap",
  blog: "/kien-thuc",
  sale: "/chuong-trinh-khuyen-mai",
  profile: "/trang-ca-nhan",
  about: "/ve-chung-toi",
  chain: "/huong-dan-do-vong-co",
  kienthuc: "/kien-thuc-kim-cuong",
  accessoryInfor: "/kien-thuc-trang-suc",
  warrantyPolicy: "/chinh-sach-bao-hanh",

  admin: "/admin",
  adminCover: "/admin-vo-kim-cuong",
  adminDiamond: "/admin-kim-cuong",
  adminAdd: "/admin-them-san-pham",
  adminmanageorder: "/admin-quan-li-don-hang",
  adminCategory: "/admin-danh-muc",
  adminCertificate: "/admin-chung-chi",
  adminUser: "/admin-nguoi-dung",
  adminbst: "/admin-bo-suu-tap",
  adminchart: "/admin-bieu-do",
  adminstatistics: "/admin-thong-ke",
  adminsale: "/admin-su-kien-sale",
  adminDiamondPrice: "/admin-gia-kim-cuong",

  productdetail: "/chi-tiet-san-pham",
  diamondprice: "/bang-gia-kim-cuong",

  notfound: "/404notfound",
  cart: "/gio-hang",
  checkout: "/tien-hanh-thanh-toan",
  priceDiamond: "/bang-gia-kim-cuong",
  saleEvent: "/chuong-trinh-khuyen-mai",
  saleProduct: "/san-pham-khuyen-mai",
  tracking: "/theo-doi-don-hang",
  saleStaff: "/nhan-vien-sale",
  deliveryStaff: "/nhan-vien-giao-hang",
  successpayment: "/thanh-toan-thanh-cong",
  failpayment: "/thanh-toan-that-bai",
  successorder: "/dat-hang-thanh-cong",
  orderhistory: "/lich-su-don-hang",
  // payment: "/thanh-toan",
  vongtay: "/san-pham-vong-tay",
  vongco: "/san-pham-vong-co",
  nhan: "/san-pham-nhan",
  khuyentai: "/san-pham-khuyen-tai",
  timkiemsanpham: "/san-pham",
  // payment: "/thanh-toan",
  saleStaffCancleOrder: "/nhan-vien-sale-huy-don",
};
